### PR TITLE
Support for `allow-popups`

### PR DESCRIPTION
**Pull request by cyril-sf**
The application can grant specific privileges to the sandbox, like opening windows.

``` js
  var sandbox = oasis.createSandbox({
    url: 'http://example.com/profile_viewer.html',
    capabilities: [ 'account' ],
    sandbox: {
      popups: true,
    }
  });
```

### CODE REVIEW

**Comment by cyril-sf** [comment]
Not ready yet. I just rebased and tested on FF and the tests don't pass.

**Comment by cyril-sf** [comment]
`allow-popups` isn't supported by Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=766282

**Comment by hjdivad** [comment]
Related we should do something when allow-same-origin and allow-scripts are both specified and the card URL is on the same origin.  I think this is effectively disabling sandboxing: which can be okay for some use cases, but not most.

**Comment by karlfreeman** [comment]
Having been digging through Oasis.js I stumbled on this after abit of head scratching. It would be good to be able to set all sandbox options through Oasis.js. in the same manner your going down @Cyril-sf.

**Comment by cyril-sf** [comment]
@karlfreeman we have put that on hold as Firefox doesn't support `allow-popups`

**Comment by hjdivad** [comment]
@karlfreeman btw we're on #conductorjs on irc in case you want something a little more realtime than github comments.

**Comment by hjdivad** [comment]
@karlfreeman supporting arbitrary sandbox flags would be great.  But lack of cross-browser support is problematic.  Cross-browser support for this stuff is already tricky.  We wouldn't want users to develop something that depends on `allow-popups` in chrome only to discover it doesn't work on Firefox.

If you have a suggestion for dealing with this, we'd love to discuss it.

**Comment by karlfreeman** [comment]
re-cc'ing the general way the IRC conversation went. Allowing `allow-same-origin` might not be too bad an idea :).

**Comment by cyoung-spciq** [comment]
It sounds like the Firefox issues with `allow-popups` are fixed now - https://bugzilla.mozilla.org/show_bug.cgi?id=766282

Could this be reevaluated?

**Comment by cyril-sf** [comment]
@cyoung-spciq Thanks for letting us know. I'll take a look.

**Comment by cyril-sf** [comment]
I've rebased and updated the code for that PR. I've also put the `allow-forms` support on a different branch (670d6afc3574b1aa16a0407da16e3095997fac9a).

This feature puts some restrictions on the browser support side: Firefox >= 27.
It can be acceptable for FF as we can assume that people get the latest versions automatically ( even though that could still be a problem for big companies which have an IT department locking browsers to a specific version).

Saucelabs seems sad, I need to take a look at this (maybe the popup blocker is activated).

**Comment by cyril-sf** [comment]
@hjdivad If you have time to review this, mostly baeb37bb6523f72ad6204ba7c34aacf2ff9397e9

**Pull request merged**
