### PR TITLE
Add `sandboxed` option, if set to false, iframe is not sandboxed

### PR DESCRIPTION
**Pull request by raycohen**
Add tests and documentation for sandboxed: false, replaces #84

### CODE REVIEW

**Comment by lukemelia** [comment]
Replaces #84

**Comment by lukemelia** [comment]
@hjdivad ping. happy to help out with maintaining this project if you want, too

**Comment by jaehess** [comment]
:+1: on getting this in. I could really use this for a couple of projects.

**Comment by jaehess** [comment]
This PR makes me sad.

**Comment by lukemelia** [comment]
Let's see what we can do about that, @jaehess. I just kicked the build. If we can get this green, I think it is mergeable.

**Comment by lukemelia** [comment]
We have a CI problem due to sauce labs being non-responsive and me not having credentials for the project's sauce labs account. I ran tests locally in latest Chrome, Safari and Firefox. Chrome passes on with both. Safari has one failure not present on master. Firefox has many tests that hang. I would like to at least have the Safari failure fixed before merging this.

**Comment by jaehess** [comment]
Thanks for trying to get this merged @lukemelia - I would like to not have to work off a fork for long...

**Comment by wagenet** [comment]
Closing due to staleness.

**Pull request closed without merging**
