### PR TITLE
Upgrade RSVP to 3.0.12

### PR DESCRIPTION
**Pull request by mixonic**

### CODE REVIEW

**Comment by stefanpenner** [comment]
3.0.13 should be out soon, IE8 bug...

**Comment by stefanpenner** [comment]
Actually oasis.js doesn't actually work in IE8 so w/e

**Comment by cyril-sf** [comment]
@stefanpenner Why do you mean by "it doesn't actually work in IE8"?

Is it the fact that it's too slow or is there something else?

**Comment by cyril-sf** [comment]
@mixonic Thanks, I'm trying to get Saucelabs to run the tests to merge it

**Comment by stefanpenner** [comment]
@Cyril-sf when I tried to get glazier working in IE8 we ran into what appeared to be internal race conditions within IE8 itself. Resulting in incredibly shitty hiesenbugs.

Yes also performance. That being said, glazier was an extremely heavy use-case, we would have 10 -> 30 sandboxes and thousands of active and ongoing requests.

**Comment by stefanpenner** [comment]
3.0.13 has been released

**Comment by cyril-sf** [comment]
Travis is unhappy, I'll check that tonight or this weekend.

**Comment by mixonic** [comment]
I'll update this for 3.0.13 as well.

**Comment by mixonic** [comment]
Updated for 3.013, parses in IE8

**Comment by cyril-sf** [comment]
Thanks @mixonic !

Can you run `grunt build` and amend the last commit with it? The `dist` file still uses `RSVP` 3.0.12.

( I'm working on improving the build tools to avoid that problem, but in the meantime we still have to push those build files )

**Comment by mixonic** [comment]
dist pushed, sorry for missing that!

**Comment by cyril-sf** [comment]
@mixonic :+1: 

You shouldn't have to think about it. It has been a pain for us for way too long...

**Pull request merged**
