### PR TITLE
[FOR DISCUSSION] Add 'sandboxed' option. If set to false, iframe is not sandboxed.

### PR DESCRIPTION
**Pull request by lukemelia**
This is useful for cases where you want oasis services but don't care about the oasis security model (i.e. you control code inside and outside the iframe).

Thoughts?

### CODE REVIEW

**Comment by lukemelia** [comment]
Ironically, this is directly related to the tag line of the project "A lightweight library for embedding untrusted content and exposing capabilities. I guess it does two things? But it does them well." I've worked on a couple of projects now where exposing capabilities is key, but content is entirely trusted.

**Comment by stefanpenner** [comment]
I am +1 on this, as sanboxed is only 1 scenario and in our experience in the far minority of cases.

**Comment by hjdivad** [comment]
I'm +1 on this as well.  There's a bit of a docs challenge in that this and a couple of other options are only relevant for the iframe adapter, but I agree it makes sense to be able to use oasis services without all the sandboxing stuff.

**Comment by lukemelia** [comment]
We are working with a client who is using conductor/oasis in this capacity
and would like to avoid a long-lived fork, so if we can agree on the
general approach to docs, config options, etc, we can get the development
work done on it. Are we comfortable with the config option proposed in this
draft PR, accompanied by appropriate docs?

**Comment by lukemelia** [comment]
Supplanted by #85

**Pull request closed without merging**
