### PR TITLE
Several fixes to correct the AMD build

### PR DESCRIPTION
**Pull request by mixonic**
- Fix some parts of the code that expected an Oasis global
- Fix some parts of the code that expected an RSVP global
- Use a shim for the UUID dependency

These changes were required for us to use Oasis without the dependencies being globals.

### CODE REVIEW

**Comment by stefanpenner** [comment]
nice.

Unsure if you have time, but we really need to upgrade the RSVP dependency, its really old/slow and has some bugs.

**Comment by cyril-sf** [comment]
@mixonic Thanks, I'm trying to get Saucelabs to run the tests to merge it

**Comment by cyril-sf** [comment]
@mixonic Feel like we're running in the same problem with the `dist` files. Can you rebase, build and amend them?

**Comment by wagenet** [comment]
Closing due to staleness.

**Pull request closed without merging**
