### PR TITLE
rsvp.js refresh

### PR DESCRIPTION
**Pull request by twokul**
- adding RSVP#rethrow
- adding promise#fail

### CODE REVIEW

**Comment by hjdivad** [comment]
Ah, okay, it looks like the problem with our setup is the same as over here: https://github.com/jzaefferer/jquery-validation/pull/767

Basically the encrypted keys in `.travis.yml` are tied to the tildeio/oasis.js repo, so only people with repo admin can run tests.

Seems very bad.  I wonder if there's any downside to just leaving the subaccount key public in the repo.

**Comment by stefanpenner** [comment]
@hjdivad that is very bad, this breaks our plan for doing this with ember.... (cc @fivetanley)

**Comment by hjdivad** [comment]
@stefanpenner confirm.  I think what we want is to create subaccounts (which we have for our open source account) and make the keys public.  **however** we would also want to tie the subaccounts to particular repos, so eg the oasisjs subaccount could only run tests on oasisjs.com

If we can't tie the subaccounts in this way, I don't think we can prevent people from abusing our open source account for private accounts, which is obviously megabad.

**Comment by hjdivad** [comment]
@stefanpenner but this is something that could be fixed on either the travis or saucelabs side.  We're good if either
1. travis let you encrypt environment variables without tying them to write access to a particular repo or
2. saucelabs let you restrict subaccounts to **only** run tests for a particular repo, and not login or access the master account, so it would be safe to make the access key public.

thoughts?

**Comment by hjdivad** [comment]
http://support.saucelabs.com/entries/25614798-How-can-we-set-up-an-open-source-account-that-runs-tests-on-people-s-pull-requests-

**Pull request closed without merging**
